dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 180.76.76.76
    - 114.114.114.114
  fallback:
    - 8.8.8.8
    - 1.1.1.1
    - 208.67.222.222
    - 94.140.14.14
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 127.0.0.1/32